services:
  client:
    build: ./client
    command: sleep infinity
    ports:
      - 3100:3100
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules
